### ISSUE TITLE
Cant upgrade 0.4.3

### ISSUE THREAD

**Issue by cloverdefa** [appleboy/CodeGPT#102]
i am use homebrow install codegpt
'''
brew tap appleboy/tap
brew install codegpt
'''
then it show me this error messanger

Error: codegpt: SHA256 mismatch
Expected: a6172371b0b9ea4c090556b0fcdae6516c3a108a728f6bbd52afeb0b5a8e8e55
  Actual: 4b518efaada8f2dd4611be9c6b4d367377625ad19185ddf4d2384af4fad9f2fd
    File: /Users/user/Library/Caches/Homebrew/downloads/3137512ca8a4413716207f21c8ab610f1ee72059e681fa42612f3f5ef65b761d--CodeGPT-0.4.3-darwin-arm64.xz

**Comment by appleboy** [comment]
I upgrade the appleboy/tap repo again.

```sh
brew untap -f appleboy/tap
brew tap appleboy/tap
brew install codegpt
```

Try it again.

**Comment by cloverdefa** [comment]
thank you
