### ISSUE TITLE
Exceeding ChatGPT API Context Length

### ISSUE THREAD

**Issue by haosheng0211** [appleboy/CodeGPT#105]
When I add too many files using git, the following error message appears:

Error: error, status code: 400, message: This model's maximum context length is 4097 tokens. However, you requested 4355 tokens (4055 in the messages, 300 in the completion). Please reduce the length of the messages or completion.

**Comment by appleboy** [comment]
Two approaches:

1. try `gpt-3.5-turbo-16k` model
2. ignore unnecessary diff codes using `git.exclude_list` config.

```sh
codegpt config set git.exclude_list xxxx
```
