### ISSUE TITLE
zh-tw commit summary show ###

### ISSUE THREAD

**Issue by cloverdefa** [appleboy/CodeGPT#108]
If the language is set to zh-tw in the .codegpt.yaml file for the commit's Summary, it will be displayed with three ### symbols on the first line, which might impact the overall readability of the commit list. Could you please advise on how to configure it in a way that prevents ### from appearing as the header on the first line?

**Comment by appleboy** [comment]
@cloverdefa Thanks for your report. I will reproduce the issue first.

**Comment by appleboy** [comment]
fixed in https://github.com/appleboy/CodeGPT/releases/tag/v0.4.4 version.
