### ISSUE TITLE
[Suggestion] Provide "codegpt config list" to list all config settings

### ISSUE THREAD

**Issue by doggy8088** [appleboy/CodeGPT#123]
I'd like to suggest you to add a `list` subcommand to list existing config settings like this:

```sh
codegpt config list
```

It will be better to mask the sensitive data such as `openai.api_key` on the output of the `codegpt config list`.

By the way, the `codegpt config` only have a `set` subcommand, but the help message didn't show that.

**Comment by appleboy** [comment]
try https://github.com/appleboy/CodeGPT/releases/tag/v0.6.0

**Comment by doggy8088** [comment]
@appleboy The openai.api_key is not masked. It's sensitive.

**Comment by appleboy** [comment]
@doggy8088 fixed in https://github.com/appleboy/CodeGPT/releases/tag/v0.6.1
