### ISSUE TITLE
Chocolatey package: CodeGPT 

### ISSUE THREAD

**Issue by doggy8088** [appleboy/CodeGPT#125]
[Chocolatey](https://chocolatey.org/) is software management automation for Windows that wraps installers, executables, zips, and scripts into compiled packages.

I made a Chocolatey package for this project: https://community.chocolatey.org/packages/codegpt

The package hasn't been approved by a moderator yet. So it might wait for a couple days to release. After it been released, I will check for new version of this repo daily by CI/CD and release to the Chocolatey repository automatically.

**Comment by doggy8088** [comment]
The windows executable been detected 2 security vendors and no sandboxes flagged this file as malicious.

https://www.virustotal.com/gui/file/ed1b6e46249b81e4a4c567933b182dca09e2e7aaf842fe6f68730229c5e26287/detection/f-ed1b6e46249b81e4a4c567933b182dca09e2e7aaf842fe6f68730229c5e26287-1698507277

**Comment by appleboy** [comment]
@doggy8088 How to fix the issue? I have no idea to fix it.

**Comment by doggy8088** [comment]
I'm in the [moderation queue](https://ch0.co/moderation) of the chocolatey right now. It could (may be) release my package soon. I'm in the second page of the 299 packages at this moment.

**Comment by doggy8088** [comment]
Good news! The very first chocolatey package already been approved TODAY.

I already pushed 0.7.0 to the Chocolatey repository. It should approved much quicker than first one.

**Comment by appleboy** [comment]
@doggy8088 Thanks. For Windows users, it is a great blessing.

**Comment by doggy8088** [comment]
https://www.virustotal.com/gui/file/701555ac291d14add3961f3fcb3bdebe2deec62315dc2b872730d5373b747509/detection

There are more **Security vendors** reported this `CodeGPT-0.7.0-windows-amd64.exe` file marked as `Malicious`. That's too bad. 😞

![image](https://github.com/appleboy/CodeGPT/assets/88981/939f7d3e-2a41-410f-8964-1705fa787c06)

**Comment by doggy8088** [comment]
@appleboy 
My package is about to removal. 🫤

> In cases where actual malware is found, the packages are subject to removal. Software sometimes has false positives. Moderators do not necessarily validate the safety of the underlying software, only that a package retrieves software from the official distribution point and/or validate embedded software against official distribution point (where distribution rights allow redistribution).

**Comment by appleboy** [comment]
This morning, I released version 0.10.0. Does this version still have the same issue?

**Comment by doggy8088** [comment]
Do you do anything different for 0.8.0?

**Comment by appleboy** [comment]
@doggy8088 Just support [Groq](https://groq.com/) API. You can reference https://github.com/appleboy/CodeGPT/releases

**Comment by appleboy** [comment]
@doggy8088 I also bump the go dependency for security issues.

**Comment by doggy8088** [comment]
What's the function calling feature for?

**Comment by appleboy** [comment]
@doggy8088 Just update the model list from OpenAI Docs that support function calling.

**Comment by doggy8088** [comment]
I scanned you latest version: `CodeGPT-0.10.0-windows-amd64.exe`

It still detected as a Malware. That's really annoying! >"<

https://www.virustotal.com/gui/file/2cbffca515103c765b28b0b8fe90783f9ca26ea119e821378d598258d3bf25ac

**Comment by appleboy** [comment]
@doggy8088 Can you re-submit or re-run the scan process?

**Comment by doggy8088** [comment]
@appleboy Did you change anything? I re-scan again. 

https://www.virustotal.com/gui/file/2cbffca515103c765b28b0b8fe90783f9ca26ea119e821378d598258d3bf25ac?nocache=1

![image](https://github.com/appleboy/CodeGPT/assets/88981/5ef6b48d-bce2-4254-95c2-5edca4b9f19b)

**Comment by doggy8088** [comment]
The `codegpt 0.10.0` has been approved. 🎉

https://community.chocolatey.org/packages/codegpt#versionhistory
