### ISSUE TITLE
How to deal with large git diff that over model's maximum context length limit?

### ISSUE THREAD

**Issue by doggy8088** [appleboy/CodeGPT#128]
When `git diff` returned too much changes. The CodeGPT will show this:

> We are trying to summarize a git diff
> Error: error, status code: 400, message: This model's maximum context length is 8192 tokens. However, your messages resulted in 28846 tokens. Please reduce the length of the messages.

Is it possible trimming the git diff result so that CodeGPT can still summarize part of the changes?

**Comment by appleboy** [comment]
Try the following config.

## update git diff_unified

```sh
codegpt config set git.diff_unified 0
```

## ignore commit file

```
codegpt config set git.exclude_list aaaa,bbbb,cccc
```

**Comment by doggy8088** [comment]
Is it possible trimming the git diff result which limiting the length of prompt text?

**Comment by matthewford** [comment]
Following on from this, could it be possible for exclude_list also to exclude directories?
