### ISSUE TITLE
essage: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by liangsj** [appleboy/CodeGPT#132]
Summarize the commit message use gpt-3.5-turbo model
We are trying to summarize a git diff
Error: error, status code: 403, message: invalid character '<' looking for beginning of value

**Comment by lqshow** [comment]
<img width="529" alt="image" src="https://github.com/appleboy/CodeGPT/assets/8086910/643202d9-a9d0-4da2-82a2-98562b63bdd2">

类似的错误

**Comment by appleboy** [comment]
@liangsj, @lqshow   openAI  Model?

**Comment by lqshow** [comment]
> @liangsj, @lqshow openAI Model?

gpt-4

**Comment by appleboy** [comment]
@lqshow Show your config by `codegpt conflig list`

**Comment by lqshow** [comment]
> @lqshow Show your config by `codegpt conflig list`

<img width="642" alt="image" src="https://github.com/appleboy/CodeGPT/assets/8086910/3fdf570c-efdb-4afa-ad3d-15edc2eebcfb">

**Comment by lqshow** [comment]
@appleboy 有没什么我可以在本地尝试做的方向吗？

**Comment by appleboy** [comment]
I tried the `gpt-4`, `gpt-4-1106-preview` and `gpt-3.5-turbo` versions and all worked.

![image](https://github.com/appleboy/CodeGPT/assets/21979/36763959-0719-464d-bb70-9abfd661e0a7)
![image](https://github.com/appleboy/CodeGPT/assets/21979/dcf1d406-d735-4c55-be93-cd9c54d9bb10)

I can't reproduce the problem. Please update the codegpt version to v0.7.0

**Comment by jimzk** [comment]
I have the same issue. The problem may due to the custom `openai.base_url`. 

@appleboy can you help with it?

**Comment by appleboy** [comment]
Show your config

**Comment by jimzk** [comment]
```
Key                       Value                  
git.diff_unified          5                      
git.exclude_list                                 
git.template_file                                
git.template_string                              
openai.api_key            ****************       
openai.api_version                               
openai.base_url           https://api.gptapi.us  
openai.frequency_penalty  <nil>                  
openai.headers                                   
openai.max_tokens         1000                   
openai.model              gpt-4                  
openai.model_name         gpt-3.5-turbo          
openai.org_id                                    
openai.presence_penalty   <nil>                  
openai.provider           openai                 
openai.proxy                                     
openai.skip_verify        false                  
openai.socks                                     
openai.temperature        1                      
openai.timeout            30s                    
openai.top_p              <nil>                  
output.lang               zh-cn 
```

**Comment by TankNee** [comment]
add v1 for your custom openai base_url
