### ISSUE TITLE
"Feature Request: Implement Shortcut Keys for Directory Level Navigation"

### ISSUE THREAD

**Issue by lyrl** [appleboy/CodeGPT#144]
Set shortcut keys for directory levels so that I can quickly navigate to the prompt I need without having to set a shortcut key for each prompt.

Official support：
![image](https://github.com/appleboy/CodeGPT/assets/1203738/02620d16-c156-436d-b503-bcb34a1b18f3)

CodeGpt: 
![image](https://github.com/appleboy/CodeGPT/assets/1203738/572680bd-3e43-4145-8498-e74af48a6617)

Expect:
![image](https://github.com/appleboy/CodeGPT/assets/1203738/aaaf8cf5-5a28-4954-8ac2-50892c374b34)

**Comment by doggy8088** [comment]
I think you posted to the wrong repo. The CodeGPT is not what you expected.
