### ISSUE TITLE
LLaMA2-70b-chat doesn't work

### ISSUE THREAD

**Issue by khorark** [appleboy/CodeGPT#154]
Hello,

The 25.04 llama model doesn't seem to be working as expected, and I think it might be because groq disabled it.
![image](https://github.com/appleboy/CodeGPT/assets/16165654/29ee392a-788d-4dd9-991c-02c6070b44c4)

Could you please update the model so we can use llama 3 instead?

![image](https://github.com/appleboy/CodeGPT/assets/16165654/cad3c48b-fd52-4551-922e-9c65efe3f726)

Thanks!

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
New model list for groq: https://console.groq.com/docs/models

**Comment by appleboy** [comment]
@khorark try https://github.com/appleboy/CodeGPT/releases/tag/v0.11.1

**Comment by khorark** [comment]
Your efficiency is impressive. Thanks for getting that done so quickly!

It's work, but only for model **llama3-70b-8192**

Model **llama3-8b-8192** doesn't work and I have this error

![image](https://github.com/appleboy/CodeGPT/assets/16165654/2534fbae-b032-42d4-b045-7bbe50f48cdd)
