### ISSUE TITLE
Lowercase the first character of first word of the commit message and remove last period

### ISSUE THREAD

**Issue by Hongbo-Miao** [appleboy/CodeGPT#17]
Take "feat: Add preview flag and remove disableCommit flag in commit command and template file."

To pass [commitlint](https://commitlint.js.org/), The first character of `Add` needs to be lowercase. And last period `.` needs to be removed.

So it would be `feat: add preview flag and remove disableCommit flag in commit command and template file`.

```shell
➜ echo 'feat: Add preview flag and remove disableCommit flag in commit command and template file.' | commitlint

⧗   input: feat: Add preview flag and remove disableCommit flag in commit command and template file.
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
✖   subject may not end with full stop [subject-full-stop]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

➜ echo 'feat: add preview flag and remove disableCommit flag in commit command and template file' | commitlint
```

<img width="685" alt="image" src="https://user-images.githubusercontent.com/3375461/224131350-811d12f8-e516-478c-9d70-b2db7a6c669c.png">

**Comment by appleboy** [comment]
See https://github.com/appleboy/CodeGPT/pull/19 and commitlint in GitHub Actions https://github.com/appleboy/CodeGPT/actions/runs/4380328191/jobs/7667270945

**Comment by appleboy** [comment]
Please try https://github.com/appleboy/CodeGPT/releases/tag/v0.0.7
