### ISSUE TITLE
Prior conversations appearing in new Chat

### ISSUE THREAD

**Issue by michellepace** [appleboy/CodeGPT#192]
Hello CodeGPT,

I have these settings:
![image](https://github.com/user-attachments/assets/f0d55a91-f46c-4cf5-876f-0dbe581164ae)

When I start a new chat, code from previous chats keep appearing:
![image](https://github.com/user-attachments/assets/72778821-7bf0-4947-a221-d7eb8241a4b8)

Regards,
Michelle

**Comment by mikluko** [comment]
@michellepace Wrong place to report. See https://codegpt.co
