### ISSUE TITLE
set azure provider err

### ISSUE THREAD

**Issue by DouDou8579** [appleboy/CodeGPT#201]
set codegpt provider azure is bad o.O

Error: error, status code: 401, status: 401 Unauthorized, message: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

**Comment by appleboy** [comment]
> Error: error, status code: 401, status: 401 Unauthorized, message: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

I believe this error message is very clear. Perhaps you could try again? I personally have verified it and there are no issues.
