### ISSUE TITLE
Support gpt-4o and gpt-4o-mini model

### ISSUE THREAD

**Issue by isarhoo** [appleboy/CodeGPT#205]
I try to use new gpt-o model, get the messages as below
```
codegpt commit --preview 
Summarize the commit message use gpt-4o model
Error: missing model

```

**Comment by appleboy** [comment]
Please post your config.

**Comment by isarhoo** [comment]
My config is
```
PS C:\Windows\System32> codegpt config list
Key                       Value
git.diff_unified          3
git.exclude_list
git.template_file
git.template_string
openai.api_key            ****************
openai.api_version
openai.base_url
openai.frequency_penalty  <nil>
openai.headers
openai.max_tokens         1000
openai.model              gpt-4o-mini
openai.model_name         gpt-4o-mini
openai.org_id
openai.presence_penalty   <nil>
openai.provider           openai
openai.proxy
openai.skip_verify        false
openai.socks
openai.temperature        1
openai.timeout            30s
openai.top_p              <nil>
output.lang               zh-tw
```

**Comment by isarhoo** [comment]
The version installed via Chocolatey is outdated. After switching to installation from the source code, gpt-4o-mini works properly.
I will close the issue now. Thank you!

**Comment by appleboy** [comment]
@doggy8088 Can you help to upgrade CodeGPT version to https://github.com/appleboy/CodeGPT/releases/tag/v0.14.6 in Chocolatey? Thanks.

**Comment by doggy8088** [comment]
Here: https://community.chocolatey.org/packages/codegpt/0.14.6
Should be publish soon. It has passed automated virus scanning.

**Comment by doggy8088** [comment]
@appleboy The `v0.14.6` package has been approved today. https://community.chocolatey.org/packages/codegpt/0.14.6

**Comment by appleboy** [comment]
@doggy8088 Thanks.
