### ISSUE TITLE
Is it possible to support "codegpt commit --amend"?

### ISSUE THREAD

**Issue by adlternative** [appleboy/CodeGPT#32]
Currently, I am facing a dilemma where if I am unsatisfied with the commit message generated by codegpt, I have to use "git reset --soft HEAD~" and then generate a new commit message using codegpt. It would be great if I could use "codegpt commit --amend" to achieve this in one step.

**Comment by appleboy** [comment]
@adlternative I will take it.

**Comment by appleboy** [comment]
try

```
codegpt commit --amend
```

**Comment by adlternative** [comment]
> try
> 
> ```
> codegpt commit --amend
> ```

Greate!
Thanks!
