### ISSUE TITLE
proxy 参数未生效

### ISSUE THREAD

**Issue by palemoky** [appleboy/CodeGPT#34]
我在`$HOME/.config/codegpt/.codegpt.yaml`中配置了代理地址，但日志显示依然请求 https://api.openai.com
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/21208635/225808557-6ac3c6ed-2e95-438d-9096-0b4af5c639a0.png">

**Comment by appleboy** [comment]
是代理位置請求 api.openai.com

**Comment by palemoky** [comment]
@appleboy 不好意思，我没明白你的意思。因为中国大陆封锁了 api.openai.com，所以我在 `.codegpt.yaml` 文件中配置了 `openai.proxy: https://proxy.example.com`，我想这样应该请求的是 proxy.example.com，我对代理的理解或使用有误吗？

**Comment by appleboy** [comment]
@palemoky 請問你是用指令，還是透過 Git Hook? 我自己個人也用 Proxy 是可以出去的。

**Comment by palemoky** [comment]
@appleboy 我刚刚尝试了 `codegpt commit --proxy https://xxx` ，同样报错显示请求的是 openai
![image](https://user-images.githubusercontent.com/21208635/225943036-bcdbaa9b-f918-434a-8344-cec62bfecc93.png)

**Comment by appleboy** [comment]
這錯誤訊息正確，你看看要不要換 base_url? https://github.com/justjavac/openai-proxy 

proxy 出去還是會連到 api.openai.com 是合理的。
