### ISSUE TITLE
Model maximum lenght

### ISSUE THREAD

**Issue by flemzord** [appleboy/CodeGPT#47]
Hello, 

I get this error quite often when I try to commit "a lot" of code. 
Is there a workaround? 

![CleanShot 2023-03-26 at 23 27 31](https://user-images.githubusercontent.com/1952914/227805633-e9bfcbf9-db45-4753-8eba-73beca2eba6e.png)

Regards, 
Maxence

**Comment by appleboy** [comment]
@flemzord 

```sh
codegpt commit --exclude_list *.c,README.md
```

separate file list by `,` symbol
