### ISSUE TITLE
Git commit title without prefix

### ISSUE THREAD

**Issue by stevenklar** [appleboy/CodeGPT#5]
Some tests of mine produced this simple commit msg output:

================Commit Summary====================

Add Swift Package Manager installation instructions and test file

- Add instructions for installing with Swift Package Manager to README.md
- Create a new file test/mycode.go

==================================================

But in this repo you are got prefixes like docs(readme): ...
How to achieve this, or do you still change this prefix manually?

Also I would like to replace readme in this example with a Ticket maybe. Any idea how it could be accomplished?

EDIT: Oh. Do you got 50 chars instead of 72 in your prompt because you added the prefix in your git commit hook?

**Comment by stevenklar** [comment]
What I use right now is more or less a hack.

```
#!/bin/sh

branch=$(git symbolic-ref --short HEAD)
ticket=$(echo $branch | grep -Eo '[A-Z]+-[0-9]+' | head -1)
type="feat"

codegpt_msg=`codegpt commit --file codegpt_msg`
codegpt_commit=`cat codegpt_msg`
commit_msg="$type($ticket): ${codegpt_commit}"

# Invoke the editor to allow the user to enter the commit message
# exec < /dev/tty && git interpret-trailers --in-place --trailer "$commit_msg"

echo "$commit_msg" > "$1"
```

**Comment by appleboy** [comment]
> But in this repo you are got prefixes like docs(readme): ...

I update the commit message manually, not AI provide.

**Comment by appleboy** [comment]
@stevenklar CodeGPT support adds a prefix in the commit title now. Please download the v0.0.5 version https://github.com/appleboy/CodeGPT/releases/tag/v0.0.5

**Comment by appleboy** [comment]
screenshot

![image](https://user-images.githubusercontent.com/21979/223928652-292c18a6-d93c-43eb-91e5-2df84451f009.png)
