### ISSUE TITLE
unexpected character string

### ISSUE THREAD

**Issue by stevecyj** [appleboy/CodeGPT#62]
Hi appleboy,

I hope this message finds you well. I wanted to bring to your attention a small issue I noticed in your latest commit with the message:

chore: add support for @nuxt-themes/docus theme

Upon reviewing the commit summary, I noticed that there is an unexpected character string 

Summarize the commit message use gpt-3.5-turbo model
We are trying to summarize a git diff
PromptTokens: 651, CompletionTokens: 14, TotalTokens: 665
We are trying to summarize a title for pull request
PromptTokens: 192, CompletionTokens: 12, TotalTokens: 204
We are trying to get conventional commit prefix
PromptTokens: 287, CompletionTokens: 2, TotalTokens: 289
================Commit Summary====================

chore: add support for @nuxt-themes/docus theme

- Add &#34;@nuxt-themes/docus&#34; dependency to package.json

==================================================

that appears in the message. This may be due to a parsing error with the tool you used to generate the commit message.

I believe that this may be resolved by ensuring that conventional commit prefixes are properly formatted in your future commits. This will help maintain consistency and clarity in your commit history.

Thank you for your attention to this matter. Please let me know if you have any questions or concerns.

Best regards

**Comment by stevecyj** [comment]
<img width="465" alt="截圖 2023-04-14 上午10 19 38" src="https://user-images.githubusercontent.com/23048888/231925244-d74090e8-bb6c-4e02-a765-b321f22be679.png">

**Comment by appleboy** [comment]
I will take it.

**Comment by stevecyj** [comment]
thx

**Comment by appleboy** [comment]
@stevecyj Try it https://github.com/appleboy/CodeGPT/releases/tag/v0.1.9
