### ISSUE TITLE
Inconsistencies in preview of Simplified Chinese and Traditional Chinese commit messages

### ISSUE THREAD

**Issue by stevecyj** [appleboy/CodeGPT#66]
Hello,

I've noticed that there are some inconsistencies in the preview of Simplified Chinese and Traditional Chinese commit messages on Github. Specifically, when I use Simplified Chinese characters in my commit message, the preview looks different from when I use Traditional Chinese characters.

 I believe this may be an issue for other users who work with Chinese characters as well.
 
![截圖 2023-04-14 下午2 53 27](https://user-images.githubusercontent.com/23048888/232418547-99b5ddd3-fd27-44c7-9978-68a8f88bbaa3.png)
![截圖 2023-04-14 下午2 53 48](https://user-images.githubusercontent.com/23048888/232418593-e7210637-cb41-4b66-ab61-968ef1415931.png)

I noticed this inconsistency when I included the phrase "GIT提交信息" in my commit message.

Could you please take a look at this issue and see if there's anything that can be done to make the preview consistent for both Simplified and Traditional Chinese characters? It would be great if the preview could accurately reflect how the commit message will appear once it's posted.

Thank you for your attention to this matter.

**Comment by appleboy** [comment]
Every execution of the command will generate a different commit message, so each translation will be converted based on the different messages, hence the result you see is normal.

**Comment by appleboy** [comment]
@stevecyj I know your point. I will check it.

**Comment by stevecyj** [comment]
thanks for your attention

**Comment by appleboy** [comment]
@stevecyj Please try the latest version.

**Comment by stevecyj** [comment]
thanks

Bo-Yi Wu ***@***.***> 於 2023年11月1日 週三 下午2:19寫道：
