### ISSUE TITLE
API Key for chat window not working

### ISSUE THREAD

**Issue by peterpahaaan** [appleboy/CodeGPT#68]
Hello,

If I enter my API Key the code generation from comments is working but everytime I try the chat window it shows that I have to enter an API key.

I tried:
- Restart VSCode
- removed & added api key
- deactivated & activated the extension

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/33236815/233182008-34e32888-9159-4d91-addd-c33c9d398bbe.png">

**Comment by appleboy** [comment]
CodeGTP is a command line tool not used in VSCode.
