### ISSUE TITLE
❓Templating capabilities

### ISSUE THREAD

**Issue by xakraz** [appleboy/CodeGPT#72]
Hi @appleboy 👋🏻 

Thanks for the tool,I 😍 it!

I am wondering what the templating capabilities are.

Would it be possible to parse stuff or to have "parameters" that would be processed by the template?
My use case is that in my company, we need to pass the Jira issue ID as part of the commit subject for later automation.

Thanks a lot for your time and considering my question 🙏🏻

**Comment by appleboy** [comment]
@xakraz Thanks for your feedback. Could you describe the detailed use case and how to achieve the purpose?

maybe add a new flag `--template_env`

```sh
codegpt commit --preview --template_file your_file_path --template_env your_env_path
```

**Comment by xakraz** [comment]
@appleboy Yes that would be super useful! 🙏🏻 

I don't know the complexity it might add to your code base but if it could also support cli-provided values like `--template-vars VAR1=value,VAR2=value,VAR3=value` that would be awesome! 😃 

(`--template_vars` and `--template_vars_file`)

As I said earlier, we need to pass the Jira issue ID as part of the commit subject for later automation.
So by example

```
codegpt commit --preview --template_file your_file_path --template_vars "TICKET_ID=ABC-1234"
```

Many thanks again for your time spent on this request 🙏🏻

**Comment by appleboy** [comment]
@xakraz I will implement this feature this week or next week. I'm sorry for the delay in response.

**Comment by appleboy** [comment]
Add custom variable to git commit message template:

```sh
{{ .summarize_prefix }}: {{ .summarize_title }}

{{ .summarize_message }}

{{ if .JIRA_URL }}{{ .JIRA_URL }}{{ end }}
```

Add custom variable to git commit message template using `--template_vars` paratemter:

```sh
codegpt commit --preview --template_file your_file_path --template_vars JIRA_URL=https://jira.example.com/ABC-123
```

Load custom variable from file using `--template_vars_file` paratemter:

```sh
codegpt commit --preview --template_file your_file_path --template_vars_file your_file_path
```

See the `template_vars_file` format as following:

```env
JIRA_URL=https://jira.example.com/ABC-123
```

**Comment by appleboy** [comment]
bump new version v0.2.1

**Comment by appleboy** [comment]
https://github.com/appleboy/CodeGPT/releases/tag/v0.2.1

**Comment by xakraz** [comment]
So many thanks 🙏🏻
