### ISSUE TITLE
Support using brew to install

### ISSUE THREAD

**Issue by Hongbo-Miao** [appleboy/CodeGPT#8]
It would be great to support using [brew](https://brew.sh/) to install, thanks! 😃

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
See the PR #10

**Comment by appleboy** [comment]
Add reference:

* https://developer.aliyun.com/article/710818
* https://github.com/sunny0826/homebrew-tap

**Comment by appleboy** [comment]
Currently, the only supported method of installation on MacOS is [Homebrew](http://brew.sh/). To install `codegpt` via brew:

```sh
brew tap appleboy/tap
brew install codegpt
```

**Comment by Hongbo-Miao** [comment]
Works perfect, thanks @appleboy ! 🚀
