### ISSUE TITLE
Option to support conventional commits

### ISSUE THREAD

**Issue by Hongbo-Miao** [appleboy/CodeGPT#9]
It would be great to support [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format! Thanks! 😃
Something like [commitgpt](https://github.com/RomanHotsiy/commitgpt) provided, can be an extra `-c`.

**Comment by appleboy** [comment]
See the PR #10

**Comment by appleboy** [comment]
conventional commits as a default function to add prefixes to commit title.

**Comment by appleboy** [comment]
https://github.com/appleboy/CodeGPT/releases/tag/v0.0.5

**Comment by Hongbo-Miao** [comment]
Hi @appleboy thanks, however, I am not sure how to use it.

I only got message like this

```shell
➜ codegpt commit
Summarize the commit message use gpt-3.5-turbo model
We are trying to summarize a git diff
We are trying to summarize a title for pull request
================Commit Summary====================

Update prefectTag version in my-values.yaml file

- Update the `prefectTag` to version `2.8.5-python3.11` in `my-values.yaml` file.

==================================================
Write the commit message to .git/COMMIT_EDITMSG file
```

In this case, the commit message is `Update prefectTag version in my-values.yaml file`, currently I copy this message and then push by `git commit -m "Update prefectTag version in my-values.yaml file".

Could you clarify how to use it? Thanks!

**Comment by appleboy** [comment]
Update document in 4343ed4
