### ISSUE TITLE
Incorrect Commit Summary Format

### ISSUE THREAD

**Issue by ryan961** [appleboy/CodeGPT#91]
![image](https://github.com/appleboy/CodeGPT/assets/32825698/67231505-daaf-49cb-ab11-59f6b9ef488b)

➜  ~ codegpt version
version: 0.2.2 commit: 50329e0

openai.model: gpt-3.5-turbo

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@ryan961 change your model to `0613`, which supports the function call. The following model version supports the function call feature.

* gpt-4-32k-0613
* gpt-4-0613
* gpt-3.5-turbo-0613
* gpt-3.5-turbo-16k-0613

**Comment by appleboy** [comment]
@ryan961 I will bump to the next version.
